# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-06 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_reminder', '0006_auto_20181106_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='extra_comments_image',
        ),
        migrations.RemoveField(
            model_name='image',
            name='time_stamp',
        ),
    ]
