# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-06 17:14
from __future__ import unicode_literals

import cvd_portal.models
import datetime
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_reminder', '0008_auto_20181106_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='time_stamp',
            field=cvd_portal.models.CustomDateTimeField(default=datetime.datetime.now),
        ),
    ]
