# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-06 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_reminder', '0009_medicine_time_stamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='medicine_id',
        ),
        migrations.AddField(
            model_name='medicine',
            name='img',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
