# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-06 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_reminder', '0010_auto_20181106_2302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='extra_comments',
            new_name='medicine_Image',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='end',
            new_name='medicine_end',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='img',
            new_name='medicine_extra_comments',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='freq',
            new_name='medicine_freq',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='name',
            new_name='medicine_name',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='start',
            new_name='medicine_start',
        ),
    ]
